export const TEAM_MEMBER = 'TEAM_MEMBER'
export const TEAM_MEMBER_SUCCESS = 'TEAM_MEMBER_SUCCESS'
export const TEAM_MEMBER_FAILURE = 'TEAM_MEMBER_FAILURE'
export const TEAM_MEMBER_RESET = 'TEAM_MEMBER_RESET'