export const PROJECT_SERVICE= 'PROJECT_SERVICE'
export const PROJECT_SERVICE_SUCCESS = 'PROJECT_SERVICE_SUCCESS'
export const PROJECT_SERVICE_FAILURE = 'PROJECT_SERVICE_FAILURE'
export const PROJECT_SERVICE_RESET = 'PROJECT_SERVICE_RESET'
