export const PROJECT_INDUSTRIES = 'PROJECT_INDUSTRIES'
export const PROJECT_INDUSTRIES_SUCCESS = 'PROJECT_INDUSTRIES_SUCCESS'
export const PROJECT_INDUSTRIES_FAILURE = 'PROJECT_INDUSTRIES_FAILURE'
export const PROJECT_INDUSTRIES_RESET = 'PROJECT_INDUSTRIES_RESET'