export const SUB_SERVICE= 'SUB_SERVICE'
export const SUB_SERVICE_SUCCESS = 'SUB_SERVICE_SUCCESS'
export const SUB_SERVICE_FAILURE = 'SUB_SERVICE_FAILURE'
export const SUB_SERVICE_RESET = 'SUB_SERVICE_RESET'
