export const GET_IN_TOUCH_DETAIL = 'GET_IN_TOUCH_DETAIL'
export const GET_IN_TOUCH_DETAIL_SUCCESS = 'GET_IN_TOUCH_DETAIL_SUCCESS'
export const GET_IN_TOUCH_DETAIL_FAILURE = 'GET_IN_TOUCH_DETAIL_FAILURE'
export const GET_IN_TOUCH_DETAIL_RESET = 'GET_IN_TOUCH_DETAIL_RESET'